// $ANTLR : "Anasint.g" -> "Anasint.java"$

	import java.util.*;
	import antlr.*;
	import javax.swing.JOptionPane;
	import javax.swing.JPanel;


public interface AnasintTokenTypes {
	int EOF = 1;
	int NULL_TREE_LOOKAHEAD = 3;
	int PROGRAMA = 4;
	int VISIBLE = 5;
	int OCULTO = 6;
	int NO_INST = 7;
	int ATRIBUTO = 8;
	int METODO = 9;
	int PROTOTIPO = 10;
	int PARAMETRO = 11;
	int PARAMETROS = 12;
	int EXPRESIONES = 13;
	int RESULTADO = 14;
	int DEFINICION = 15;
	int VACIO = 16;
	int VARIABLE_LOCAL = 17;
	int VARIABLES_LOCALES = 18;
	int INSTRUCCION = 19;
	int INSTRUCCIONES = 20;
	int MENOSUNARIO = 21;
	int LLAMADA = 22;
	int ACCESO_TABLA = 23;
	int ACCESO_OBJETO = 24;
	int ACCESO_SIMPLE = 25;
	int LISTA_ENTEROS = 26;
	int MODULO = 27;
	int IDENT = 28;
	int INST = 29;
	int CLASE = 30;
	int LLAVE_ABIERTA = 31;
	int LLAVE_CERRADA = 32;
	int PARENTESIS_ABIERTO = 33;
	int PUNTO_Y_COMA = 34;
	int PARENTESIS_CERRADO = 35;
	int DEV = 36;
	int COMA = 37;
	int ASIGNACION = 38;
	int SI = 39;
	int ENTONCES = 40;
	int SINO = 41;
	int FINSI = 42;
	int MIENTRAS = 43;
	int HACER = 44;
	int FINMIENTRAS = 45;
	int O = 46;
	int Y = 47;
	int NO = 48;
	int MAYOR = 49;
	int MAYOR_IGUAL = 50;
	int MENOR = 51;
	int MENOR_IGUAL = 52;
	int IGUAL = 53;
	int DISTINTO = 54;
	int MAS = 55;
	int MENOS = 56;
	int POR = 57;
	int DIVISION = 58;
	int CORCHETE_ABIERTO = 59;
	int LIT_ENTERO = 60;
	int LIT_REAL = 61;
	int LIT_CAR = 62;
	int CIERTO = 63;
	int FALSO = 64;
	int CORCHETE_CERRADO = 65;
	int PUNTO = 66;
	int ENTERO = 67;
	int REAL = 68;
	int LOGICO = 69;
	int CARACTER = 70;
	int FORMACION = 71;
}
