// $ANTLR : "Anasint.g" -> "Anasint.java"$

	import java.util.*;
	import antlr.*;
	import javax.swing.JOptionPane;
	import javax.swing.JPanel;

public interface AnasintTokenTypes {
	int EOF = 1;
	int NULL_TREE_LOOKAHEAD = 3;
	int PROGRAMA = 4;
	int DECLARACION = 5;
	int CONSTANTE = 6;
	int DEC_TIPO = 7;
	int TIPO = 8;
	int VARIABLE = 9;
	int FUNC = 10;
	int CUERPO = 11;
	int RANGO_ENTERO = 12;
	int RANGO_CARACTER = 13;
	int ACCESO_SIMPLE = 14;
	int ACCESO_REGISTRO = 15;
	int ACCESO_ARRAY = 16;
	int ACCESO_ARRAY_REGISTRO = 17;
	int LLAMADA = 18;
	int ARGUMENTOS = 19;
	int ASIG = 20;
	int CONTENIDO = 21;
	int INSTRUCCION = 22;
	int CABECERA = 23;
	int CAMPO = 24;
	int CONST = 25;
	int IDENT = 26;
	int IGUAL = 27;
	int PUNTO_Y_COMA = 28;
	int TYPE = 29;
	int REGISTRO = 30;
	int END = 31;
	int VAR = 32;
	int COMA = 33;
	int FUNCION = 34;
	int PARENTESIS_ABIERTO = 35;
	int PARENTESIS_CERRADO = 36;
	int BEGIN = 37;
	int ENTERO = 38;
	int REAL = 39;
	int BOOLEANO = 40;
	int CARACTER = 41;
	int MENOS = 42;
	int LIT_ENTERO = 43;
	int PUNTO = 44;
	int LIT_CARACTER = 45;
	int ARRAY = 46;
	int CORCHETE_ABIERTO = 47;
	int CORCHETE_CERRADO = 48;
	int OF = 49;
	int CADENA = 50;
	int ASIGNACION = 51;
	int LEER = 52;
	int ESCRIBIR = 53;
	int SI = 54;
	int SINO = 55;
	int MIENTRAS = 56;
	int HACER = 57;
	int DESDE = 58;
	int HASTA = 59;
	int ATRAS = 60;
	int OR = 61;
	int AND = 62;
	int NOT = 63;
	int MAYOR = 64;
	int MAYOR_IGUAL = 65;
	int MENOR = 66;
	int MENOR_IGUAL = 67;
	int DISTINTO = 68;
	int MAS = 69;
	int POR = 70;
	int DIVISION = 71;
	int LIT_REAL = 72;
	int CIERTO = 73;
	int FALSO = 74;
}
